export const QUOTES = [
  "The curious paradox is that when I accept myself just as I am, then I can change. — Carl Rogers",
  "Everything that irritates us about others can lead us to an understanding of ourselves. — Carl Jung",
  "The best way to predict your future is to create it. — Peter Drucker",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
  "Your visions will become clear only when you can look into your own heart. — Carl Jung",
  "The shoe that fits one person pinches another; there is no recipe for living that suits all cases. — Carl Jung",
  "Knowing your own darkness is the best method for dealing with the darknesses of other people. — Carl Jung",
  "I am not what happened to me, I am what I choose to become. — Carl Jung",
  "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed. — Carl Jung",
  "Between stimulus and response there is a space. In that space is our power to choose our response. — Viktor Frankl",
  "He who has a why to live for can bear almost any how. — Friedrich Nietzsche",
  "The privilege of a lifetime is to become who you truly are. — Carl Jung",
  "The most important relationship you will ever have is the one you have with yourself. — Diane Von Furstenberg",
  "Vulnerability is not winning or losing; it's having the courage to show up and be seen when we have no control over the outcome. — Brene Brown",
  "What you resist, persists. — Carl Jung",
  "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances, to choose one’s own way. — Viktor Frankl",
  "When we are no longer able to change a situation, we are challenged to change ourselves. — Viktor Frankl",
  "Tell me, what is it you plan to do with your one wild and precious life? — Mary Oliver",
  "Someone I loved once gave me a box full of darkness. It took me years to understand that this too, was a gift. — Mary Oliver",
  "You do not have to be good. You do not have to walk on your knees for a hundred miles through the desert, repenting. You only have to let the soft animal of your body love what it loves. — Mary Oliver",
  "Listen—are you breathing just a little, and calling it a life? — Mary Oliver",
  "We all have an infant inside of us, but the infant doesn't have to run the show. — Murray Bowen",
  "That which is created in a relationship can be fixed in a relationship. — Murray Bowen",
  "You have inherited a lifetime of tribulation. Everybody has inherited it. Take it over, make the most of it and when you have decided you know the right way, do the best you can with it. — Murray Bowen",
  "Until you make the unconscious conscious, it will direct your life and you will call it fate. — Carl Jung",
  "Despair is the price one pays for self-awareness. Look deeply into life, and you'll always find despair. — Irvin Yalom",
  "The act of revealing oneself fully to another and still being accepted may be the major vehicle of therapeutic help. — Irvin Yalom"
];
