#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "❌ You are trying to push directly to 'main'. Pushing to 'main' is prohibited."
  echo "Please use a Pull Request to merge changes into 'main'."
  exit 1
fi
